theme: jekyll-theme-minimal
lang: en
title: Ryan T. Allen
description: "Ryan T. Allen | Assistant Professor at BYU | Research on AI, Innovation, and Data-Driven Organizations"
author: Ryan T. Allen
logo: /ryan_allen_portrait.jpg
url: https://www.ryantallen.com
social:
  name: Ryan T. Allen
  links:
    - https://scholar.google.com/citations?user=4cp9vjwAAAAJ
    - https://www.linkedin.com/in/ryantallen/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
 -
   scope:
     path: "*.pdf"
   values:
     sitemap: false
 -
   scope:
     path: ""
   values:
     image: /ryan_allen_portrait.jpg
