theme: jekyll-theme-minimal
lang: en
title: Ryan T. Allen
description: "Ryan T. Allen | Assistant Professor at BYU | Research on AI, Innovation, and Data-Driven Organizations"
logo: /ryan_allen_portrait.jpg
# Analytics
google_analytics: G-2VE8B6C6RX
url: https://www.ryantallen.com
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
 -
   scope:
     path: "*.pdf"
   values:
     sitemap: false
